version: '2'
services:
  hadoorbirdproxy:
    image: basschipper/homeassistant-doorbird-proxy:0.4
    ports:
      - ${PROXY_PORT}:80
    restart: always
    environment:
      HA_API_URL: ${HA_API_URL}
      HA_ACCESS_TOKEN: ${HA_ACCESS_TOKEN}
      HA_DOORBELL_ENTITY: ${HA_DOORBELL_ENTITY}
      HA_FRONTDOORMOTION_ENTITY: ${HA_FRONTDOORMOTION_ENTITY}
      HA_FRONTDOOROPEN_ENTITY: ${HA_FRONTDOOROPEN_ENTITY}